### ISSUE TITLE
Unable to log in via GitHub

### ISSUE THREAD

**Issue by masonwheeler** [apxltd/what-bugs#159]
Logging in to the forum works fine, but when attempting to log in to the main site to post a comment on a story, the GitHub link causes a 500 error.

**Comment by BenLubar** [comment]
Can't reproduce 😕

**Comment by masonwheeler** [comment]
Just reproduced at 1:56 PM, Eastern Time.  Can you see the error it made for me in the server logs?

**Comment by boomzillawtf** [comment]
I can't see anything there regarding a github login.

**Comment by masonwheeler** [comment]
Beautiful.  So it's not logging errors. x.x

**Comment by BenLubar** [comment]
@boomzillawtf you have access to the front page logs? O_o

@masonwheeler I found something that looks relevant at 1:54 PM Eastern:

```text
Exception information: 
    Exception type: JsonSerializationException 
    Exception message: Required property 'name' expects a value but got null. Path '', line 1, position 1152.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndObject(Object newObject, JsonReader reader, JsonObjectContract contract, Int32 initialDepth, Dictionary`2 propertiesPresence)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TheDailyWtf.Controllers.ArticlesController.<LoginGitHub>b__13_0(HttpClient client, String token) in C:\ProgramData\InedoAgent\BuildMaster\Temp\_E67457\Src\TheDailyWtf\Controllers\ArticlesController.cs:line 198
   at TheDailyWtf.OAuth2.OAuth2Login(ArticlesController controller, Endpoint endpoint, Func`3 login) in C:\ProgramData\InedoAgent\BuildMaster\Temp\_E67457\Src\TheDailyWtf\Common\OAuth2.cs:line 80
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<BeginInvokeActionMethodWithFilters>b__36(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<>c__DisplayClass2a.<BeginInvokeAction>b__20()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   at System.Web.Mvc.MvcHandler.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
 ```

Looks like GitHub is giving us `null` for your display name.

**Comment by masonwheeler** [comment]
Yeah, I don't have a display name filled out on my profile.  So apparently the forum is able to deal with that gracefully but the main site can't?

**Comment by masonwheeler** [comment]
This issue is not fixed.  It just happened again.

**Comment by BenLubar** [comment]
@apapadimoulis may need to deploy.

**Comment by masonwheeler** [comment]
Nearly 3 weeks later, this is still failing.  The issue shouldn't be closed until the bug is fixed.

**Comment by BenLubar** [comment]
Ok, I did my first deployment from http://buildmaster/applications/224/builds/build?releaseNumber=2016.25&buildNumber=1

@masonwheeler Tell me if it worked.

**Comment by masonwheeler** [comment]
This time I was able to log in, but it redirected me back to the front page instead of the comments page I was logging in from.  But I suppose that's an entirely different issue.
